inherit_from: ./configs/TUM_RGBD/tum.yaml
mode: mono
scene: freiburg1_room
only_tracking: False
offline_mapping: False
offline_video: video.npz
wandb: True

data:
  input_folder: rgbd_dataset_freiburg1_room
cam:
  H: 480 
  W: 640 
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  distortion: [0.2624, -0.9531, -0.0054, 0.0026, 1.1633]
