verbose: True
dataset: 'tumrgbd'
mode: 'mono'
stride: 1
max_frames: -1
setting: median_filter

mapping:
  device: "cuda:0"
  BA: False
  geo_iter_ratio: 0.3
  color_refine: True
  ckpt_freq: 2000
  mapping_window_size: 10
  pixels: 2000
  iters_first: 500
  geo_iter_first: 200
  iters: 300

tracking:
  gt_camera: False
  device: "cuda:0"
  buffer: 600
  beta: 0.75
  warmup: 12
  upsample: True
  motion_filter:
    thresh: 4.0  # add as keyframe if avg flow >= 4.0 pixels
  multiview_filter:
    thresh: 0.03  # dpeth error < 0.01m
    visible_num: 2  # points viewed by at least 2 cameras
    kernel_size: 1
    bound_enlarge_scale: 1.20
  frontend:
    enable_loop: True
    enable_online_ba: True
    keyframe_thresh: 3.0
    thresh: 16.0
    window: 25
    radius: 2
    nms: 1
  backend:
    final_ba: True
    thresh: 25.0
    radius: 1
    nms: 5
    # used for loop detection
    loop_window: 25
    loop_thresh: 25.0  # only consider edge with avg flow < 50.0 pixels
    loop_radius: 1
    loop_nms: 10
    enable_depth_prior: True
    normalize: False
  f2m:
    vis_freq: 40
    vis_inside_freq: 50
    separate_LR: True
    pixels: 5000
    iters: 200
    lr: 0.001

cam:  #NOTE: intrinsic is different per scene in TUM
  # refer to https://vision.in.tum.de/data/datasets/rgbd-dataset/file_formats#intrinsic_camera_calibration_of_the_kinect
  png_depth_scale: 5000.0 #for depth image in png format
  ### target/output camera settings, camera_size -> resize -> crop -> target_size
  H_edge: 8
  W_edge: 8
  H_out: 384
  W_out: 512

rendering:
  N_samples: 24
  N_surface: 48

meshing:
  eval_rec: False
  resolution: 1024  # change to 2048 for higher resolution geometry
  get_largest_components: False
  remove_small_geometry_threshold: 0.2
  n_points_to_eval: 200000
  mesh_threshold_to_eval: 0.05
  forecast_radius: 25

mono_prior:
  depth: omnidata
  normal: False
  depth_pretrained: ./pretrained/omnidata_dpt_depth_v2.ckpt
  normal_pretrained: ./pretrained/omnidata_dpt_normal_v2.ckpt
  predict_online: False

data:
  dataset_path: /gpfs/work5/0/prjs0799/expert_data/datasets/TUM_RGBD
  output: /gpfs/work5/0/prjs0799/expert_output/TUM_RGBD
