inherit_from: configs/TUM_RGBD/tum.yaml
mode: rgbd
scene: freiburg1_desk2
only_tracking: False
offline_mapping: False
offline_video: video.npz
wandb: True
setting: fixed_expert
expname: expF_f2f_freiburg1_desk2

data:
  input_folder: rgbd_dataset_freiburg1_desk2
  use_tmpdir_proxy: True
cam:
  H: 480 
  W: 640 
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  distortion: [0.2624, -0.9531, -0.0054, 0.0026, 1.1633]

tracking:
  warmup: 6
  motion_filter:
    thresh: 4.0

  f2f:
    wait_until_warmup: True

  pose_init:
    const_speed_assumption: False
    pose_hist: f2f

  pose_mixing:
    method: f2f
