inherit_from: configs/TUM_RGBD/tum.yaml
mode: rgbd
scene: freiburg3_office
only_tracking: False
offline_mapping: False
offline_video: video.npz
wandb: True
setting: fixed_expert
expname: expF_gtinit_freiburg3_office

data:
  input_folder: rgbd_dataset_freiburg3_long_office_household
  use_tmpdir_proxy: True
cam:  #intrinsic is different per scene in TUM, this cam does not have distortion
  H: 480 
  W: 640 
  fx: 535.4
  fy: 539.2
  cx: 320.1
  cy: 247.6

tracking:
  warmup: 6
  motion_filter:
    thresh: 4.0

  pose_init:
    pose_hist: gt

  pose_mixing:
    method: mean
