inherit_from: configs/Replica/replica.yaml
mode: rgbd
scene: room2
only_tracking: False
offline_mapping: False
offline_video: video.npz
wandb: True


meshing:
  gt_mesh_path: /gpfs/work5/0/prjs0799/expert_data/cull_replica_mesh/room2.ply
data:
  input_folder: room2