inherit_from: configs/TUM_RGBD/tum.yaml
mode: rgbd
scene: freiburg1_desk
only_tracking: False
offline_mapping: False
offline_video: video.npz
wandb: True
setting: psnr_expert
expname: expP_freiburg1_desk

data:
  input_folder: rgbd_dataset_freiburg1_desk
  use_tmpdir_proxy: True
cam:
  H: 480 
  W: 640 
  fx: 517.3
  fy: 516.5
  cx: 318.6
  cy: 255.3
  distortion: [0.2624, -0.9531, -0.0054, 0.0026, 1.1633]

tracking:
  warmup: 6
  motion_filter:
    thresh: 4.0

  pose_mixing:
    method: psnr
    psnr_criterion_metric: psnr_masked
