output: /gpfs/work5/0/prjs0799/expert_output/ExpertTester
setting: learned_expert_tester
expname: replica

setup_seed: 43

test:
  scenes: [
    "configs/Replica/office1.yaml",
    "configs/Replica/office2.yaml",
    "configs/Replica/office3.yaml",
    "configs/Replica/office4.yaml",
  ]
  batch_size: 32  # for testing

  data_gen:
    pose_init:
      pose_hist: mix
    pose_mixing:
      mapped_pose: mix
